# -*- coding: utf-8 -*-
"""task3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cg3zo8YWg8BclMC9ZcwN8lT3Zu_MolxF
"""

#3
inp=open("input3.txt", "r") 
out=open("output3.txt", "w")
v= inp.readline().split()
r=int(v[0])
con=int(v[1])
dic={}
for i in range(con-1):
  store=inp.readline().split()
  #print(dic)
  if int(store[0]) not in dic:
    dic[int(store[0])]=[int(store[1])]
  else:
    dic[int(store[0])].append(int(store[1]))
  if int(store[1]) not in dic: 
      dic[int(store[1])]=[int(store[0])]
  else:
      dic[int(store[1])].append(int(store[0]))
#print(dic)
visited=[]
def dfs(visited, dic, node):
  if node not in visited:
    print(node,end=" ",file=out)
    visited.append(node)
    for neighbour in dic[node]:
      dfs(visited, dic, neighbour)
dfs(visited, dic, 1)