# -*- coding: utf-8 -*-
"""task1B

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KaKuXbvT4owveFa6hGu5bxLQUoZNPGJ0
"""

#1(b)
f = open("input1_b.txt", "r")
out=open("output1_b.txt", "w")
g = f.readline()
val=g.split()
n=int(val[0])
c=int(val[1])
li=[[] for i in range(n+1)]
counter = 0
while (counter<c):
    a,b,c = f.readline().split() # reading each line
    c = c.strip() # getting rid of \n from the end
    a=int(a)
    b=int(b)
    c=int(c)
    li[a].append((b,c))
    counter+=1

for i in range(len(li)):
   string=f"{i}: "
   if len(li[i])==0:
     string+=" "
   else:
     for j in li[i]:
       string=string+str(j)+" "
   print(string, file=out)