# -*- coding: utf-8 -*-
"""task4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GPRd6RBmqkZM5OhKywDvEsF2-KvgnUNP
"""

#4 
inp=open("/content/drive/MyDrive/A. Shihab work station/lab ass 4 files/input4.txt", "r")
out=open("/content/drive/MyDrive/A. Shihab work station/lab ass 4 files/output4.txt", "w")
v= inp.readline().split()
r=int(v[0])
con=int(v[1])
dic={}
for i in range(con):
  store=inp.readline().split()
  if int(store[0]) not in dic:
    dic[int(store[0])]=[int(store[1])]
    if int(store[1]) not in dic:
      dic[int(store[1])]=[]
  else:
    dic[int(store[0])].append(int(store[1]))
    if int(store[1]) not in dic:
      dic[int(store[1])]=[]
# print(dic)
visited=[]
def dfs(visited, dic, node):
  if node not in visited:
    visited.append(node)
    for neighbour in dic[node]:
      return dfs(visited, dic, neighbour)
  else:
    return 0 
x=dfs(visited, dic, 1)
if x==0:
  print("YES THERE IS CYCLE",file=out)
else:
  print("NO CYCLE",file=out)