# -*- coding: utf-8 -*-
"""task5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C0OmKNwrP2p5hNGvKFc2ywFo-_72fux8
"""

#5
from queue import Queue
inp=open("input5.txt", "r")
out=open("output5.txt", "w")
v= inp.readline().split()
r=int(v[0])
con=int(v[1])
d=int(v[2])
mat = [[0 for _ in range(r)] for _ in range(r)]
for i in range(con):
  store=inp.readline().split()
  mat[int(store[0])-1][int(store[1])-1]=1
  mat[int(store[1])-1][int(store[0])-1]=1
#print(mat)  
s=1
colour=[0]*r
time=[0]*r
parent=[0]*r
q=Queue()
colour[0]=1
q.put(1)
while not q.empty():
  u=q.get()
  #print(u,end=" ")
  for i in range(r):
    if mat[u-1][i]==1:
      if colour[i]==0:
        colour[i]=1
        time[i]=time[u-1]+1
        parent[i]=u
        q.put(i+1)
# print("time arr:",time)
# print("Parent:",parent)
print("Time:",time[d-1], file=out)
store=[d]
c=d-1
while parent[c]!=0:
  c=parent[c]-1
  store.append(c+1)
print("shortest Path:",end=" ",file=out)
for i in range(len(store)-1,-1,-1):
  print(store[i],end=" ",file=out)