# -*- coding: utf-8 -*-
"""task1A

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14lJ93NZaQc8tJ-5CbtPBOEv-P6RZYp8K
"""

#1(a)
f = open("input1_a.txt", "r")
outp=open("output1_a.txt", "w")
n = f.readline()
val=n.split()
rows = int(val[0])+1
cols = rows
mat = [[0 for _ in range(cols)] for _ in range(rows)]
for i in range(int(val[1])):
  store=f.readline().split()
  mat[int(store[0])][int(store[1])]=int(store[2])
for i in range(rows):
  for j in range (rows):
    print(mat[i][j],end=' ', file=outp)
  print("\n",file=outp)