# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ZnJfZPNUH-_gI5Z5m_eb71VLZe0Jgl-
"""

#1
input= open("input1.txt",'r')
out= open("output1.txt", 'w')
n= input.readline()
id= input.readline()
id_li=id.split()
m=input.readline()
marks=m.split()
for i in range(0, int(n)-1):
  temp=marks[i+1]
  temp_2= id_li[i+1]
  j=i
  while j>=0:
    if int(marks[j])<int(temp):
      marks[j+1]=marks[j]
      id_li[j+1]=id_li[j] 
    else:
      break
    j=j-1
  marks[j+1]=temp
  id_li[j+1]=temp_2


str=""
for i in id_li:
  str+=f"{(i)} "
print(str, file=out)