# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ReewmWX6e8GdRXk3UZSu98hFnqReGbY
"""

#2
input= open("input2.txt",'r')
out= open("output2.txt", 'w')
n= input.readline()
val= input.readline()
b= val.split()

a=[]
for i in b:
  a.append(int(i))

def merge(a, p, q, r):
  n1= q-p+1
  n2= r-q
  l=[0]*(n1+1)
  x=[0]*(n2+1)
  for i in range(0, n1):
    l[i]=a[p+i]
  for j in range(0, n2):
    x[j]=a[q+j+1]
  l[n1]=float('inf')
  x[n2]=float('inf')

  j=0
  i=0
  for k in range(p,r+1):
    if (l[i])<=(x[j]):
      a[k]=l[i]
      i=i+1
    else:
      a[k]=x[j]
      j=j+1

def merge_sort(a,p,r):
  if p<r:
    q=(p+r)//2
    merge_sort(a, p, q)
    merge_sort(a, q+1, r)
    merge(a, p, q , r)

merge_sort(a, 0,len(a)-1 )
str=''
for i in a:
  str+=f"{i} "
print(str, file=out)