# -*- coding: utf-8 -*-
"""task4(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EUvHN7Xrfh4pzyE-2MOZo0kDJ_fAN5so
"""

input = open('input4.txt', 'r')
out= open("output4(b).txt","w")
read = (input.readlines())
store = []
for i in read:
  temp=i.strip()
  s_li=temp.split()
  store.append(s_li)
h_queue= []    #main queue
h_list = store #initial checking

def h_checker():
    for i in h_list:
        if i[1] == 'doctor':
            heapsort_seeDoctor(h_queue)    
        else:
            h_queue.append(i) 
 
def heapsort_seeDoctor(arr):
    for i in range(int(len(arr)/2)-1, -1, -1):
        heapify(arr, len(arr), i)
    for j in range(len(arr)-1, 0, -1):
        arr[j], arr[0] = arr[0], arr[j]
        heapify(arr, j, 0)
    print("See Doctor:",h_queue[0][0],file=out)
    remove = h_queue.pop(0)

def heapify(lst, n, i):
    largest = i
    left = 2*i+1
    right = 2*i+2
    if left < n and int(lst[i][1]) < int(lst[left][1]):
        largest = left
    if right < n and int(lst[largest][1]) < int(lst[right][1]):
        largest = right
    if largest != i:
        lst[i], lst[largest] = lst[largest], lst[i]
        heapify(lst, n, largest)

def printQueue(li):
    for i in li:
        print('Name:',i[0],'',i[1])    

h_checker()
#printQueue(h_queue)