# -*- coding: utf-8 -*-
"""task 1(b)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G62YKOGDVvcXERC30g2C6Sv2IJzsgxXU
"""

#1 (b)
input=open("/content/drive/MyDrive/Cse221 Lab /Lab assignment 1/input1b.txt","r")
output=open("/content/drive/MyDrive/Cse221 Lab /Lab assignment 1/output1b.txt","w")
list= input.readlines()
lines=int(list[0])
for i in range(1,lines+1):
  op= list[i].split()
  if op[2]=="+":
    store= int(op[1])+int(op[3])
  elif op[2]=="-":
    store= int(op[1])-int(op[3])
  elif op[2]=="/":
    store= int(op[1])/int(op[3])
  elif op[2]=="*":
    store= int(op[1])* int(op[3])

  a=op[1]
  b=op[3]
  opera=op[2]
  hold=f"The result of {a} {opera} {b} is {store}"
  print(hold,file= output)