# -*- coding: utf-8 -*-
"""task 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/188gENmlIVgqGA_AuaY61E4EXw8SbYj0X
"""

#4
inputfile=open("/content/drive/MyDrive/Cse221 Lab /Lab assignment 1/input4.txt",'r')
output=open("/content/drive/MyDrive/Cse221 Lab /Lab assignment 1/output4.txt",'w')
n= inputfile.readline()
li= inputfile.readlines()
ids=li[0].split()
marks=li[1].split()
#---------------
                              
for i in range(len(marks)-1): 
  max=i
  for j in range(i+1,len(marks)):
    if int(marks[i])<int(marks[j]):
      max=j
  marks[i],marks[max]=marks[max],marks[i]
  ids[i],ids[max]=ids[max],ids[i]

#-------------------
for i in range(len(marks)-1):
  min=i
  for j in range(i+1,len(marks)):
    if marks[i]!=marks[j]:
      break
    else:
      if ids[i]>ids[j]:
        min=j
  ids[i],ids[min]=ids[min],ids[i]

#--------------------------------
string=""
for i in range(len(ids)):
  string+= f"ID:{int(ids[i])} Mark:{int(marks[i])}\n"

print(string, file=output)