# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MF8l-aSbcc4ODECRk0JcrVaQJMSj9n-f
"""

#4
import math
input=open("input4.txt","r")
out=open("output4.txt","w")
arr=[]
for i in range(3):
  a,b=input.readline().split()
  a=int(a)
  b=int(b)
  if a==0 and b==0:
    pass
  elif a<0 or b>=100000 or a>b:
    pass
  else:
    count=0
    for i in range(a,b+1):
      temp= math.sqrt(i)
      if temp.is_integer():
        count+=1
    print(count,file=out)