# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MF8l-aSbcc4ODECRk0JcrVaQJMSj9n-f
"""

#3
inp=open("input3.txt","r")
out=open("output3.txt","w")
n=inp.readline()
temp=inp.readline().split()
string=inp.readline()
arr=[]
for i in temp:
  arr.append(int(i))
arr.sort()
jack=[]
jack_count=0
jill_count=0
idx=0
seq=[]
for p in string:
  if p=="J":
    jack.append(arr[idx])
    jack_count+=arr[idx]
    seq.append(arr[idx])
    idx+=1

  else:
    temp=jack.pop()
    seq.append(temp)
    jill_count+=temp
for i in seq:
  print(i,end="",file=out)
print("",file=out)
print(f"Jack will work for {jack_count} hours",file=out)
print(f"Jill will work for {jill_count} hours",file=out)