# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rf75zSifJ9242SvrpvBIc3W7C20t9Te1
"""

#1
inp=open("input1.txt","r")
out=open("output1.txt","w")
dic={}
queue=[]
extra=[]
for i in range(18):
  v_1,v_2,edge=inp.readline().split()
  if v_1 not in queue:
    queue.append(v_1)
    extra.append(v_1)
  if v_2 not in queue:
    queue.append(v_2)
    extra.append(v_2)
  if v_1 not in dic:
    dic[v_1]=[(v_2,int(edge))]
  else:
    dic[v_1].append((v_2,int(edge))) 
# print(dic)
d=[1000]*len(queue)
p=[0]*len(queue)
d[0]=0
def Not_empty(arr):
  flag=False
  for i in arr:
    if i!=0:
      flag=True
      break
    else:
      flag=False
  return flag

while Not_empty(queue):
  min=10**10
  idx=None
  for i in range(len(d)):
    if d[i]<min:
      if queue[i]!=0:
        min=d[i]
        idx=i
  u=queue[idx]
  queue[idx]=0 
  d_u=d[idx]
  if u in dic.keys():
    adj=dic[u]
    for tup in adj:
      v_idx=extra.index(tup[0])
      d_v=d[v_idx]
      if d_v>d_u+tup[1]:
        d[v_idx]=d_u+tup[1]
        p[v_idx]=u
  else:
    pass
# print(d,"FINAL D")
# print(p,"FINAL P")
source="Motijheel"
last=extra.index("MOGHBAZAR")
path=["MOGHBAZAR"]
cost=0
val="MOGHBAZAR"
while val!="Motijheel":
  val=p[last]
  path.append(val)
  cost+=d[last]
  last=extra.index(val)
print("Path:", end=" ",file=out)
for i in range(len(path)-1,-1,-1):
  print(path[i],end=" ",file=out)
print(" ",file=out)
print("Cost:",cost,file=out)

from google.colab import drive
drive.mount('/content/drive')